import fs from 'node:fs';
import path from 'node:path';
const read=n=>JSON.parse(fs.readFileSync(`content/${n}.json`,'utf8'));
const profile=read('profile'),projects=read('projects'),gallery=read('gallery'),pubs=read('publications');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const base=('/'+(process.env.BASE_PATH??profile.basePath??'').replace(/^\/+|\/+$/g,'')).replace(/\/$/,'');
const url=p=>`${base}/${p}`;
const links=[['','Home'],['research/','Research'],['projects/','Industry projects'],['publications/','Publications'],['about/','About & CV'],['contact/','Contact']];
const card=p=>`<a class="project-card" href="${url(`projects/${p.id}/`)}"><div class="card-top"><span class="eyebrow">${esc(p.category==='research'?'RESEARCH '+p.number:'PROJECT '+p.number)}</span><span class="status">${esc(p.status)}</span></div><h3>${esc(p.title)}</h3><p>${esc(p.summary)}</p><div class="card-foot"><span>${esc(p.tags)}</span><span aria-hidden="true">↗</span></div></a>`;
const mast=(label,title,desc)=>`<header class="page-heading"><span class="eyebrow">${label}</span><h1>${title}</h1><p>${desc}</p></header>`;
function page(route,title,description,body){const active=route.startsWith('projects/')&&route!=='projects/'?projects.find(p=>route===`projects/${p.id}/`)?.category==='research'?'research/':'projects/':route;
const canonical=profile.siteUrl?`${profile.siteUrl.replace(/\/$/,'')}${url(route)}`:'';
const html=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${esc(title)} | ${esc(profile.name)}</title><meta name="description" content="${esc(description)}"><meta property="og:title" content="${esc(title)} | ${esc(profile.name)}"><meta property="og:description" content="${esc(description)}"><meta property="og:type" content="website">${canonical?`<link rel="canonical" href="${esc(canonical)}"><meta property="og:url" content="${esc(canonical)}">`:''}<meta name="theme-color" content="#172d3b"><link rel="icon" href="${url('assets/favicon.svg')}" type="image/svg+xml"><link rel="stylesheet" href="${url('assets/style.css')}"><script defer src="${url('assets/gallery.js')}"></script></head><body><a class="skip" href="#main">Skip to content</a><header class="site-header"><a class="wordmark" href="${url('')}">Kishan Deka<span>RESEARCH & ENGINEERING</span></a><nav aria-label="Main navigation">${links.map(([r,l])=>`<a href="${url(r)}" ${active===r?'aria-current="page"':''}>${l}</a>`).join('')}</nav></header><main id="main">${body}</main><footer><a class="wordmark" href="${url('')}">Kishan Deka</a><span>Cosmology · Data science · Scientific computing</span><a href="${url('contact/')}">Get in touch ↗</a></footer></body></html>`;
const target=`dist/${route}index.html`;fs.mkdirSync(path.dirname(target),{recursive:true});fs.writeFileSync(target,html);}
function galleryMarkup(){return `<section class="gallery" aria-label="Scientific media gallery" data-gallery="${url('assets/gallery.json')}" data-base="${base}"><div class="gallery-top"><span class="eyebrow">RESEARCH IN VIEW</span><a href="${url('gallery/')}">Browse gallery ↗</a></div><div class="gallery-stage" id="gallery-stage"></div><div class="gallery-bottom"><div><span class="eyebrow" id="gallery-label"></span><h3 id="gallery-title"></h3><p id="gallery-caption"></p><a id="gallery-project">Explore project ↗</a></div><div class="gallery-controls"><button type="button" data-prev aria-label="Previous slide">←</button><span id="gallery-count" aria-live="polite"></span><button type="button" data-next aria-label="Next slide">→</button></div></div><div class="thumbnails" aria-label="Choose a slide"></div><noscript><p>Enable JavaScript to use the media gallery. Research pages remain available from the navigation.</p></noscript></section>`;}
page('','Computational cosmology, applied to data',profile.intro,`<section class="hero"><div><span class="eyebrow">COSMOLOGY RESEARCHER · WARSAW, POLAND</span><h1>Finding signals.<br><em>Building understanding.</em></h1><p class="lead">${esc(profile.intro)}</p><div class="actions"><a class="button" href="${url('research/')}">Explore my research <span>↗</span></a><a class="text-link" href="${url('projects/')}">Industry projects ↗</a></div></div><aside class="hero-note"><span class="small-rule"></span><p>From the cosmic microwave background to practical machine learning.</p><span>PhD researcher at NCBJ<br>6+ years working with Python</span><a href="${url('about/')}">About me & CV ↗</a></aside></section>${galleryMarkup()}<section class="section"><div class="section-heading"><div><span class="eyebrow">01 / SCIENTIFIC WORK</span><h2>Questions on a cosmic scale.</h2></div><a href="${url('research/')}">All research ↗</a></div><div class="cards">${projects.filter(p=>p.category==='research').slice(0,2).map(card).join('')}</div></section><section class="section"><div class="section-heading"><div><span class="eyebrow">02 / APPLIED PROJECTS</span><h2>The same rigor. New problems.</h2></div><a href="${url('projects/')}">All projects ↗</a></div><div class="cards three">${projects.filter(p=>p.category==='industry').map(card).join('')}</div></section><section class="closing"><h2>Science is where I learned<br>to ask better questions.</h2><div><p>I’m bringing that curiosity to data science, machine learning, and analytics—with a focus on careful evaluation and understandable results.</p><a href="${url('about/')}">More about my background ↗</a></div></section>`);
page('research/','Research','CMB lensing, foregrounds, delensing, and scientific computing.',`${mast('01 / RESEARCH','Understanding the Universe,<br>one signal at a time.','I develop computational and statistical methods to extract cosmological information from complex observations.')}<div class="cards">${projects.filter(p=>p.category==='research').map(card).join('')}</div>`);
page('projects/','Industry projects','Data analytics, streaming fraud detection, and computer vision projects.',`${mast('02 / INDUSTRY PROJECTS','Research habits.<br>Practical applications.','A developing collection of projects in analytics, machine learning, and data engineering. Each project documents its intended workflow, evaluation, and next steps.')}<div class="cards">${projects.filter(p=>p.category==='industry').map(card).join('')}</div>`);
for(const p of projects)page(`projects/${p.id}/`,p.title,p.summary,`<a class="back" href="${url(p.category==='research'?'research/':'projects/')}">← ${p.category==='research'?'Research':'Industry projects'}</a>${mast(esc(p.status).toUpperCase(),esc(p.title),esc(p.summary))}<div class="detail-layout"><aside><span class="eyebrow">FOCUS & METHODS</span><p>${esc(p.tags)}</p>${p.links.map(l=>`<p><a href="${esc(l.url)}">${esc(l.label)} ↗</a></p>`).join('')}<a href="${url('gallery/')}">View media gallery ↗</a></aside><article>${Object.entries(p.sections).map(([h,t])=>`<section><h2>${esc(h)}</h2><p>${esc(t)}</p></section>`).join('')}</article></div>`);
const records=(arr,empty)=>arr.length?arr.map(x=>`<article class="record"><span class="eyebrow">${esc(x.year)} · ${esc(x.status??'')}</span><h3>${esc(x.title)}</h3><p>${esc(x.authors??'')} ${esc(x.venue??'')}</p>${x.url?`<a href="${esc(x.url)}">Read more ↗</a>`:''}</article>`).join(''):`<div class="empty"><h3>${empty}</h3><p>Verified titles, authors, dates, and links will be added here.</p></div>`;
page('publications/','Publications & talks','Publications, presentations, and scientific communication.',`${mast('03 / PUBLICATIONS & TALKS','Research, shared.','A place for papers, conference presentations, and scientific discussions.')}<section class="section compact"><h2>Publications</h2>${records(pubs.publications,'Publication records coming soon')}</section><section class="section compact"><h2>Selected talks & posters</h2>${records(pubs.talks,'Talk and poster details coming soon')}</section>`);
const doc=(value,label)=>value?`<a class="button" href="${url(value)}" download>${label} ↓</a>`:`<div class="document-placeholder"><strong>${label}</strong><span>Document not yet added</span></div>`;
page('about/','About & CV','Kishan Deka: cosmology researcher and computational scientist.',`${mast('04 / ABOUT','Curiosity, grounded<br>in computation.','I am Kishan Deka, a PhD researcher in cosmology at the National Centre for Nuclear Research (NCBJ), Warsaw.')}<div class="detail-layout"><aside><span class="eyebrow">AT A GLANCE</span><p>Warsaw, Poland<br>6+ years of Python<br>Cosmology & scientific computing</p></aside><article><section><h2>From research to real-world data</h2><p>My work brings together CMB gravitational lensing, Galactic foregrounds, B-mode delensing, and cross-correlations with large-scale structure. I build simulation and analysis workflows to understand what noisy observations can tell us—and where uncertainty remains.</p><p>I am developing a portfolio in data science, machine learning, and analytics, applying the same emphasis on reproducibility, careful debugging, and statistical evaluation.</p></section><section><h2>Skills, in context</h2><dl class="skills"><dt>Statistical modeling</dt><dd>Bayesian inference, likelihood analysis, uncertainty quantification, and correlation functions.</dd><dt>Scientific computing</dt><dd>Python, numerical simulations, large-scale data processing, and signal processing.</dd><dt>Machine learning projects</dt><dd>Classification, neural networks, explainability, and model evaluation.</dd><dt>Data engineering projects</dt><dd>SQL workflows, streaming architectures, reproducible environments, and CI/CD.</dd></dl></section><section id="cv"><h2>Curriculum vitae & resume</h2><div class="documents">${doc(profile.academicCV,'Academic CV')}${doc(profile.industryResume,'Industry resume')}</div></section></article></div>`);
page('contact/','Contact','Contact and professional profiles for Kishan Deka.',`${mast('05 / CONTACT','Let’s compare notes.','For conversations about cosmology, scientific computing, or opportunities in data science and machine learning.')}<div class="contact-list">${[['email','Email'],['github','GitHub'],['linkedin','LinkedIn'],['scholar','Academic profile']].map(([k,l])=>`<div><h2>${l}</h2>${profile[k]?`<a href="${esc(k==='email'?'mailto:'+profile[k]:profile[k])}">${esc(profile[k])} ↗</a>`:'<span>Contact detail not yet added</span>'}</div>`).join('')}</div>`);
page('gallery/','Simulation gallery','Scientific figures, simulations, and visual explanations.',`${mast('RESEARCH IN VIEW','A window into the work.','Figures and moving images from scientific computing. Media slots below are ready for the original research assets.')}<label class="filter-label">Filter by topic <select id="gallery-filter"><option value="all">All topics</option>${[...new Set(gallery.map(g=>g.category))].map(c=>`<option>${esc(c)}</option>`).join('')}</select></label>${galleryMarkup()}`);
fs.writeFileSync('dist/assets/gallery.json',JSON.stringify(gallery,null,2));
fs.writeFileSync('dist/404.html',`<!doctype html><html lang="en"><meta charset="utf-8"><title>Page not found</title><link rel="stylesheet" href="${url('assets/style.css')}"><main><h1>Page not found.</h1><a href="${url('')}">Return home</a></main></html>`);
console.log(`Generated ${6+projects.length+1} pages; base path: ${base||'/'}`);
