import fs from 'node:fs';
import path from 'node:path';

const read = name => JSON.parse(fs.readFileSync(`content/${name}.json`, 'utf8'));
const profile = read('profile'), projects = read('projects'), pubs = read('publications'), about = read('about'), gallery = read('gallery');
const esc = s => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const base = ('/' + (process.env.BASE_PATH ?? profile.basePath ?? '').replace(/^\/+|\/+$/g, '')).replace(/\/$/, '');
const url = p => `${base}/${p}`;
const asset = p => /^https?:/.test(p) ? p : url(p);
const external = 'target="_blank" rel="noopener noreferrer"';
const paths = {
  github:'M12 .297C5.37.297 0 5.67 0 12.297c0 5.303 3.438 9.8 8.205 11.385.6.113.82-.258.82-.577 0-.285-.01-1.04-.015-2.04-3.338.724-4.043-1.61-4.043-1.61-.546-1.387-1.333-1.756-1.333-1.756-1.09-.745.083-.729.083-.729 1.205.084 1.838 1.237 1.838 1.237 1.07 1.835 2.807 1.305 3.492.998.108-.776.42-1.305.763-1.605-2.665-.305-5.467-1.334-5.467-5.93 0-1.31.468-2.38 1.235-3.22-.123-.303-.535-1.523.117-3.176 0 0 1.008-.322 3.301 1.23a11.52 11.52 0 0 1 3.003-.404c1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.654 1.653.242 2.873.119 3.176.77.84 1.233 1.91 1.233 3.22 0 4.609-2.807 5.622-5.479 5.92.43.372.823 1.102.823 2.222 0 1.606-.015 2.898-.015 3.293 0 .322.216.694.825.576C20.565 22.092 24 17.596 24 12.297c0-6.627-5.373-12-12-12',
  linkedin:'M20.447 20.452h-3.554v-5.569c0-1.328-.027-3.037-1.852-3.037-1.853 0-2.136 1.445-2.136 2.939v5.667H9.351V9h3.414v1.561h.046c.477-.9 1.637-1.85 3.37-1.85 3.601 0 4.267 2.37 4.267 5.455v6.286zM5.337 7.433a2.062 2.062 0 1 1 0-4.124 2.062 2.062 0 0 1 0 4.124zM7.119 20.452H3.555V9h3.564v11.452zM22.225 0H1.771C.792 0 0 .774 0 1.729v20.542C0 23.227.792 24 1.771 24h20.451C23.2 24 24 23.227 24 22.271V1.729C24 .774 23.2 0 22.222 0z',
  orcid:'M12 0C5.373 0 0 5.373 0 12s5.373 12 12 12 12-5.373 12-12S18.627 0 12 0zM7.369 4.378c.525 0 .947.431.947.947s-.422.947-.947.947-.947-.431-.947-.947.422-.947.947-.947zm-.722 3.281h1.444v10.041H6.647V7.659zm3.563 0h3.9c3.712 0 5.344 2.653 5.344 5.025 0 2.578-2.016 5.016-5.325 5.016H10.21V7.659zm1.444 1.303v7.444h2.297c3.272 0 4.022-2.484 4.022-3.722 0-2.016-1.284-3.722-4.097-3.722h-2.222z'
};
function icon(name) { return name === 'email' ? '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" aria-hidden="true"><rect x="2" y="4" width="20" height="16" rx="2"/><path d="m2 7 9 6a2 2 0 0 0 2 0l9-6"/></svg>' : `<svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="${paths[name]}"/></svg>`; }
const socialNames = [['github','GitHub'],['linkedin','LinkedIn'],['email','Email'],['orcid','ORCID']];
const socialHref = key => key === 'email' ? `mailto:${profile[key]}` : profile[key];
const socials = () => `<div class="socials" aria-label="Professional profiles">${socialNames.filter(([k])=>profile[k]).map(([k,n])=>`<a href="${esc(socialHref(k))}" ${k==='email'?'':external} aria-label="${n}" title="${n}">${icon(k)}<span class="sr-only">${n}</span></a>`).join('')}</div>`;
function github(p) {
  const repo = p.github || p.links.find(l => /^https:\/\/github\.com\/[^/]+\/[^/?#]+/.test(l.url))?.url;
  return `<div class="repo-link"><a class="github-button" href="${esc(repo || profile.github)}" ${external} aria-label="${repo?'GitHub repository for '+p.title:'Kishan Deka on GitHub'}">${icon('github')}<span>GitHub</span></a></div>`;
}
const workflows = {
  foregrounds:{label:'Signal separation', input:['CMB sky','Galactic emission','Instrument noise'], core:'Component separation', output:['Lensing reconstruction','B-mode delensing']},
  'tomographic-delensing':{label:'Complementary tracers', input:['Galaxy redshift bins','CMB observations'], core:'Tomographic cross-correlation', output:['Weighted lensing tracer','Delensing template']},
  'psf-modeling':{label:'Precision photometry', input:['Stellar images','Instrument response'], core:'PSF model fitting', output:['Flux measurements','Residual validation']},
  dynamo:{label:'Numerical experiments', input:['Initial magnetic field','Flow configuration'], core:'2D dynamo · C++ solver', output:['Python bindings','Simulation visualization']},
  retention:{label:'Decision analytics', input:['Customer records','Experiment outcomes'], core:'SQL · PCA · Churn model', output:['SHAP explanations','Retention decisions']},
  paywatch:{label:'Streaming inference', input:['Transaction stream','Rolling features'], core:'LSTM autoencoder → XGBoost', output:['Fraud scores','PostgreSQL audit log']},
  disasterlens:{label:'Reproducible computer vision', input:['AIDERv2 images','Augmentation'], core:'ResNet50 · PyTorch', output:['Model evaluation','CI/CD · Streamlit']}
};
function diagram(p) {
  const w=workflows[p.id];
  if (!w) return `<div class="workflow"><span class="eyebrow">${esc(p.tags)}</span><h3>${esc(p.title)}</h3></div>`;
  return `<div class="workflow" role="img" aria-label="Workflow schematic: ${esc(w.input.join(' and '))} feed ${esc(w.core)}, leading to ${esc(w.output.join(' and '))}. Not measured results."><div class="workflow-label">${esc(w.label)}</div><div class="workflow-inputs">${w.input.map(t=>`<span>${esc(t)}</span>`).join('')}</div><div class="workflow-connector" aria-hidden="true"></div><div class="workflow-core">${esc(w.core)}</div><div class="workflow-connector" aria-hidden="true"></div><div class="workflow-outputs">${w.output.map(t=>`<span>${esc(t)}</span>`).join('')}</div><small>WORKFLOW SCHEMATIC</small></div>`;
}
function visual(p) {
  const g=gallery.find(g=>g.project===p.id && g.src && g.type!=='placeholder');
  if (!g) return diagram(p);
  if (['video','mp4','webm'].includes(g.type)) return `<video controls playsinline preload="metadata" ${g.poster?`poster="${esc(asset(g.poster))}"`:''} aria-label="${esc(g.alt)}"><source src="${esc(asset(g.src))}"></video>`;
  return `<img class="project-image" src="${esc(asset(g.type==='gif'&&g.poster?g.poster:g.src))}" alt="${esc(g.alt)}" loading="lazy">`;
}
const research = projects.filter(p=>p.category==='research'), industry=projects.filter(p=>p.category==='industry');
const detailUrl=p=>url(`projects/${p.id}/`);
function carousel(id,title,items,all) {
  return `<section class="showcase" data-carousel aria-roledescription="carousel" aria-labelledby="${id}-title"><div class="section-heading"><h2 id="${id}-title"><span class="section-number">${id==='selected-research'?'01':'02'}</span>${title}</h2><a class="text-link" href="${url(all)}">View all <span aria-hidden="true">↗</span></a></div><div class="slide-window"><div class="slide-track">${items.map((p,i)=>`<article class="slide" aria-roledescription="slide" aria-label="${i+1} of ${items.length}" ${i?'inert aria-hidden="true"':'aria-hidden="false"'}><div class="slide-visual">${visual(p)}</div><div class="slide-copy"><span class="eyebrow">${esc(p.tags)}</span><h3><a href="${detailUrl(p)}">${esc(p.title)}</a></h3><p>${esc(p.summary)}</p><a class="text-link" href="${detailUrl(p)}">Read the project <span aria-hidden="true">↗</span></a>${github(p)}</div></article>`).join('')}</div></div><div class="carousel-bar"><div class="slide-dots" role="group" aria-label="Choose ${title.toLowerCase()}">${items.map((p,i)=>`<button type="button" data-slide="${i}" aria-label="Show ${esc(p.title)}" aria-pressed="${i===0}"><span></span></button>`).join('')}</div><div class="slide-controls"><span data-count>01 / ${String(items.length).padStart(2,'0')}</span><button type="button" data-prev aria-label="Previous ${title.toLowerCase()} slide">←</button><button type="button" data-next aria-label="Next ${title.toLowerCase()} slide">→</button><button type="button" data-play>Play</button></div></div><span class="sr-only" data-announcement aria-live="polite"></span></section>`;
}
const nav=[['','Profile'],['about/','About'],['research/','Research'],['projects/','Projects'],['publications/','Publications & talks'],['contact/','Contact']];
function page(route,title,description,body) {
  const active=route.startsWith('projects/')&&route!=='projects/'?(projects.find(p=>route===`projects/${p.id}/`)?.category==='research'?'research/':'projects/'):route;
  const canonical=profile.siteUrl?`${profile.siteUrl.replace(/\/$/,'')}${url(route)}`:'';
  const html=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)} | ${esc(profile.name)}</title><meta name="description" content="${esc(description)}"><meta property="og:title" content="${esc(title)} | ${esc(profile.name)}"><meta property="og:description" content="${esc(description)}"><meta property="og:type" content="website">${canonical?`<link rel="canonical" href="${esc(canonical)}"><meta property="og:url" content="${esc(canonical)}">`:''}<meta name="theme-color" content="#141618"><link rel="icon" href="${url('assets/favicon.svg')}" type="image/svg+xml"><link rel="stylesheet" href="${url('assets/style.css')}"><script defer src="${url('assets/site.js')}"></script>${route==='gallery/'?`<script defer src="${url('assets/gallery.js')}"></script>`:''}</head><body><a class="skip" href="#main">Skip to content</a><header class="site-header"><a class="wordmark" href="${url('')}">Kishan Deka<span>.</span></a><nav aria-label="Main navigation">${nav.map(([r,n])=>`<a href="${url(r)}" ${active===r?'aria-current="page"':''}>${n}</a>`).join('')}</nav></header><main id="main">${body}</main><footer><span>Kishan Deka · Warsaw, Poland</span><span>Cosmology · Data science · Scientific computing</span><a href="${url('gallery/')}">Media gallery</a></footer></body></html>`;
  const target=`dist/${route}index.html`;fs.mkdirSync(path.dirname(target),{recursive:true});fs.writeFileSync(target,html);
}
const mast=(label,title,description)=>`<header class="page-heading"><span class="eyebrow">${label}</span><h1>${title}</h1><p>${description}</p></header>`;
const portrait=profile.portrait?`<img src="${esc(asset(profile.portrait))}" alt="${esc(profile.portraitAlt)}" width="290" height="350" fetchpriority="high">${profile.portraitIsDemo?'<span class="demo-label">Demo portrait</span>':''}`:'<div class="portrait-pending" role="img" aria-label="Portrait not yet supplied"><span>KD</span><small>Portrait to be added</small></div>';
page('','Profile',profile.intro,`<section class="hero"><div class="hero-copy"><span class="eyebrow">COSMOLOGY · DATA · COMPUTATION</span><h1>Finding signals.<br><em>Building understanding.</em></h1><p class="lead">I’m Kishan, a PhD researcher at the National Centre for Nuclear Research in Warsaw. I study CMB lensing and build computational tools to recover meaningful signals from complex, noisy data.</p><p class="hero-secondary">My work connects cosmology, statistical inference, and scientific computing with projects in data science and machine learning.</p><a class="text-link" href="${url('about/')}">More about me <span aria-hidden="true">↗</span></a></div><aside class="portrait-block"><div class="portrait">${portrait}</div>${socials()}<p>NCBJ · Warsaw, Poland</p></aside></section>${carousel('selected-research','Selected research',research,'research/')}${carousel('selected-projects','Selected industry projects',industry,'projects/')}`);
function card(p) {return `<article class="project-card"><a class="card-visual" href="${detailUrl(p)}" aria-label="Explore ${esc(p.title)}">${visual(p)}</a><div class="card-copy"><span class="eyebrow">${esc(p.tags)}</span><h2><a href="${detailUrl(p)}">${esc(p.title)}</a></h2><p>${esc(p.summary)}</p><div class="card-actions"><a class="text-link" href="${detailUrl(p)}">Read the project ↗</a>${github(p)}</div></div></article>`;}
page('research/','Research','CMB lensing, Galactic foregrounds, delensing, and scientific computing.',`${mast('RESEARCH','Understanding the Universe,<br><em>one signal at a time.</em>','I develop simulation and analysis methods to recover cosmological information from complex observations.')}<div class="project-grid">${research.map(card).join('')}</div>`);
page('projects/','Industry projects','Analytics, streaming fraud detection, and computer vision.',`${mast('INDUSTRY PROJECTS','Research habits.<br><em>Practical applications.</em>','Data analytics, machine learning, and engineering projects built around careful evaluation and reproducible workflows.')}<div class="project-grid">${industry.map(card).join('')}</div>`);
for(const p of projects) {
  const sections=Object.entries(p.sections).filter(([h,t])=>!['Results & evidence'].includes(h));
  page(`projects/${p.id}/`,p.title,p.summary,`<a class="back" href="${url(p.category==='research'?'research/':'projects/')}">← ${p.category==='research'?'Research':'Industry projects'}</a>${mast(esc(p.tags),esc(p.title),esc(p.summary))}<div class="detail-layout"><aside><div class="detail-visual">${visual(p)}</div>${github(p)}${p.links.filter(l=>!l.url.includes('github.com')).map(l=>`<p><a class="text-link" href="${esc(l.url)}" ${external}>${esc(l.label)} ↗</a></p>`).join('')}<a class="text-link" href="${url('gallery/')}">Research media gallery ↗</a></aside><article>${sections.map(([h,t])=>`<section><h2>${esc(h)}</h2><p>${esc(t)}</p></section>`).join('')}${p.id==='foregrounds'?`<section><h2>Publication</h2><p>${esc(pubs.publications[0].title)}</p><a class="text-link" href="${esc(pubs.publications[0].url)}" ${external}>Read the paper ↗</a></section>`:''}</article></div>`);
}
const records=arr=>arr.map(x=>`<article class="record"><div class="record-year">${esc(x.year||'Seminar')}</div><div><span class="eyebrow">${esc(x.status)}</span><h3>${x.url?`<a href="${esc(x.url)}" ${external}>${esc(x.title)}</a>`:esc(x.title)}</h3>${x.authors?`<p>${esc(x.authors)}</p>`:''}<p>${esc(x.venue)}</p>${x.url?`<a class="text-link" href="${esc(x.url)}" ${external}>Read publication ↗</a>`:''}</div></article>`).join('');
page('publications/','Publications & talks','Selected papers, conference presentations, and invited seminars.',`${mast('PUBLICATIONS & TALKS','Research, <em>shared.</em>','Papers, invited seminars, and conference presentations in cosmology and theoretical physics.')}<div class="page-jumps"><a href="#papers">Publications</a><a href="#talks">Talks & seminars</a></div><section class="content-section" id="papers"><h2>Selected publications</h2>${records(pubs.publications)}<p class="source-note">Publication status follows the supplied academic CV.</p></section><section class="content-section" id="talks"><h2>Talks & seminars</h2>${records(pubs.talks)}</section>`);
const timeline=items=>items.map(x=>`<article class="timeline-row"><span>${esc(x.dates)}</span><div><h3>${esc(x.title)}</h3><p class="institution">${esc(x.institution)}</p><p>${esc(x.description)}</p></div></article>`).join('');
const list=items=>`<ul class="plain-list">${items.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`;
const skillGrid=`<div class="skill-filters" role="group" aria-label="Filter technical expertise">${['All','Languages','Libraries','Tools'].map((s,i)=>`<button type="button" data-skill-filter="${s}" aria-pressed="${i===0}">${s}</button>`).join('')}</div><div class="skill-grid">${about.skills.map(s=>`<div class="skill-item" data-skill-category="${esc(s.category)}"><span class="skill-logo" aria-hidden="true"><span>${esc(s.mark)}</span>${s.icon?`<img src="https://cdn.jsdelivr.net/gh/devicons/devicon@v2.17.0/icons/${esc(s.icon)}" alt="" loading="lazy" width="48" height="48" data-brand-logo>`:''}</span><span>${esc(s.name)}</span></div>`).join('')}</div><span class="sr-only" data-skill-status aria-live="polite"></span>`;
const doc=(value,label)=>value?`<a class="button" href="${esc(asset(value))}" download>${label}<span aria-hidden="true">↓</span></a>`:'';
page('about/','About','Education, experience, technical expertise, academic CV, and industry resume.',`${mast('ABOUT','Curiosity, grounded<br><em>in computation.</em>','I’m a cosmology researcher with over six years of Python experience, working at the intersection of physics, statistical inference, and large-scale data analysis.')}<section class="about-intro"><h2>From cosmic signals<br>to real-world data.</h2><div><p>My PhD focuses on weak gravitational lensing of the cosmic microwave background, Galactic foregrounds, B-mode delensing, and cross-correlations with large-scale structure. I build end-to-end simulations and analysis pipelines to understand both the signal and the uncertainty behind a result.</p><p>I am also developing projects in data analytics, machine learning, and data engineering. I bring a strong analytical background, careful debugging, and experience communicating technical findings to international audiences.</p></div></section><section class="content-section"><h2>Education</h2>${timeline(about.education)}</section><section class="content-section"><h2>Research experience</h2>${timeline(about.experience)}</section><section class="content-section" id="skills"><div class="section-heading"><h2>Technical expertise</h2><span class="source-note">Languages, packages & tools from my academic CV</span></div>${skillGrid}</section><section class="content-section two-column"><div><h2>Research visits</h2>${list(about.visits)}<p>Collaboration experience with LSST DESC and CMB-S4.</p></div><div><h2>Fellowships & awards</h2>${list(about.awards)}</div></section><section class="content-section"><h2>Teaching & communication</h2><p>Teaching assistant for undergraduate Classical Electrodynamics with Prof. Andrzej Hryczuk at NCBJ, Fall 2025. Experience presenting scientific findings in invited seminars and international conferences.</p><a class="text-link" href="${url('publications/')}#talks">Selected talks ↗</a></section><section class="content-section cv-section" id="cv"><div><span class="eyebrow">DOWNLOAD</span><h2>CV & resume</h2><p>Academic background and industry-focused experience.</p></div><div class="documents">${doc(profile.academicCV,'Academic CV')}${doc(profile.industryResume,'Industry resume')}</div></section>`);
page('contact/','Contact','Contact Kishan Deka and explore his professional profiles.',`${mast('CONTACT','Let’s <em>compare notes.</em>','For conversations about cosmology, scientific computing, and opportunities in data science or machine learning.')}<div class="contact-list">${socialNames.filter(([k])=>profile[k]).map(([k,n])=>`<a href="${esc(socialHref(k))}" ${k==='email'?'':external}><span class="contact-name">${icon(k)}<span>${n}</span></span><span class="contact-value">${esc(k==='email'?profile[k]:k==='github'?'KishanDeka':k==='linkedin'?'Kishan Deka':'0000-0002-8229-4326')} <span aria-hidden="true">↗</span></span></a>`).join('')}</div><p class="contact-location">National Centre for Nuclear Research · Warsaw, Poland</p>`);
function galleryMarkup(){return `<section class="gallery" aria-label="Scientific media gallery" data-gallery="${url('assets/gallery.json')}" data-base="${base}"><div class="gallery-stage" id="gallery-stage"></div><div class="gallery-bottom"><div><span class="eyebrow" id="gallery-label"></span><h3 id="gallery-title"></h3><p id="gallery-caption"></p><a class="text-link" id="gallery-project">Explore project ↗</a></div><div class="gallery-controls"><button type="button" data-prev aria-label="Previous slide">←</button><span id="gallery-count" aria-live="polite"></span><button type="button" data-next aria-label="Next slide">→</button></div></div><div class="thumbnails" aria-label="Choose a slide"></div><noscript><p>Enable JavaScript to use the media gallery. All project pages remain available from the navigation.</p></noscript></section>`;}
page('gallery/','Research media gallery','Scientific figures and simulation media.',`${mast('MEDIA GALLERY','A window into <em>the work.</em>','Original research figures and simulation media. The current entries mark where your original assets can be added.')}<label class="filter-label">Filter by topic <select id="gallery-filter"><option value="all">All topics</option>${[...new Set(gallery.map(g=>g.category))].map(c=>`<option>${esc(c)}</option>`).join('')}</select></label>${galleryMarkup()}`);
fs.mkdirSync('dist/assets',{recursive:true});
fs.writeFileSync('dist/assets/gallery.json',JSON.stringify(gallery,null,2));
fs.writeFileSync('dist/404.html',`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Page not found | Kishan Deka</title><link rel="stylesheet" href="${url('assets/style.css')}"></head><body><main class="page-heading"><h1>Page not found.</h1><a class="text-link" href="${url('')}">Return to profile</a></main></body></html>`);
console.log(`Generated ${7+projects.length} editorial pages; base path: ${base||'/'}`);
